### ISSUE TITLE
Athletics calculations add proficiency twice

### ISSUE THREAD

**Issue by jonbonazza** [kkragenbrink/roll20-writh-custom#57]
When rolling an athletics check, if you are proficient in athletics, the proficiency bonus is being added twice. For instance, Iz has a STR of +4, and a +2 prof bonus, but this is is athletics roll:
![str](https://user-images.githubusercontent.com/1424843/34637351-3ba3eae6-f269-11e7-9db3-533eb70d1803.png)

**Comment by nivthefox** [comment]
Fixed.
